# Tarea - Programación lineal

### Diseño de la Dieta Óptima

Se quiere producir comida para gatos de la manera más barata, no obstante se debe también asegurar que se cumplan los datos requeridos de analisis nutricional. Por lo que se quiere variar la cantidad de cada ingrediente para cumplir con los estandares nutricionales. Los requisitos que se tienen es que en $100$ gramos, se deben tener **por lo menos** $8$ gramos de proteína y $6$ gramos de grasa. Así mismo, no se debe tener más de $2$ gramos de fibra y $0.4$ gramos de sal.  

Los datos nutricionales se pueden obtener de la siguiente tabla:

Ingrediente|Proteína|Grasa|Fibra|Sal
:----|----|----|----|----
Pollo|  10.0%|08.0%|00.1%|00.2%
Carne|  20.0%|10.0%|00.5%|00.5%
Cordero|15.0%|11.0%|00.5%|00.7%
Arroz|  00.0%|01.0%|10.0%|00.2%
Trigo|  04.0%|01.0%|15.0%|00.8%
Gel|    00.0%|00.0%|00.0%|00.0%

Los costos de cada producto son:

Ingrediente|Costo por gramo
:----|----
Pollo|$\$$0.013
Carne|$\$$0.008
Cordero|$\$$0.010
Arroz|$\$$0.002
Trigo|$\$$0.005
Gel|$\$$0.001    

Lo que se busca optimizar en este caso es la cantidad de productos que se debe utilizar en la comida de gato, minimizando el costo total. Para simplificar la notación use las siguientes variables: 

+ $x_1:$ Gramos de pollo  
+ $x_2:$ Gramos de carne  
+ $x_3:$ Gramos de cordero  
+ $x_4:$ Gramos de arroz  
+ $x_5:$ Gramos de trigo  
+ $x_6:$ Gramos de gel

La tarea consiste en plantear el problemade programación lineal que permita satisfacer las necesidades alimenticias del gato al tiempo que minimice el costo total y resolverlo con `linprog`.

In [32]:
import numpy as np
import scipy.optimize as opt

In [33]:
c= np.array ([.013,
             .008,
             .010,
             .002,
             .005,
             .001])
A= np.array ([[-.10,  -.20,  -.15, 0,  -.04,  0], 
              [-.08, -.10,  -.11, -.01,  -.01, 0 ], 
              [.001,  .005,  .005,  .10,  .15, 0], 
              [ .002,  .005,  .007,  .002,  .008, 0],
              [ -1,  -1,  -1,  -1,  -1, -1 ]])
b = np.array ([-8,
              -6,
              2,
              4,
              -100])
respuesta = opt.linprog(c, A, b, method="simplex")

In [34]:
respuesta.x

array([ 0., 60.,  0.,  0.,  0., 40.])

### Problema de distribución de energía eléctrica

La Comisión Federal de Electricidad **(CFE)** dispone de cuatro plantas de generación para satisfacer la demanda diaria eléctrica en cuatro ciudades, Guadalajara, León y Morelia. Las plantas $1$, $2$ y $3$ pueden satisfacer $80$, $40$ y $60$ millones de KW al día respectivamente. Las necesidades de las ciudades de Guadalajara, León y Morelia son de $70$, $40$ y $70$ millones de Kw al día respectivamente. 


Los costos asociados al envío de suministro energético por cada millón de Kw entre cada planta y cada ciudad son los registrados en la siguiente tabla. 

-|Guadalajara|León|Morelia
:----|----|----|----
Planta 1|5|2|7
Planta 2|3|6|6
Planta 3|6|1|2

Y por último, las restricciones del problema, van a estar dadas por las capacidades de oferta y demanda de cada planta (en millones de KW) y cada ciudad.

Para simplificar la notación use las siguientes variables:

+ $x_1$: Kw (en millones) distribuidos de la Planta 1 a Guadalajara
+ $x_2$: Kw (en millones) distribuidos de la Planta 1 a León
+ $x_3$: Kw (en millones) distribuidos de la Planta 1 a Morelia
+ $x_4$: Kw (en millones) distribuidos de la Planta 2 a Guadalajara
+ $x_5$: Kw (en millones) distribuidos de la Planta 2 a León
+ $x_6$: Kw (en millones) distribuidos de la Planta 2 a Morelia
+ $x_7$: Kw (en millones) distribuidos de la Planta 3 a Guadalajara
+ $x_8$: Kw (en millones) distribuidos de la Planta 3 a León
+ $x_9$: Kw (en millones) distribuidos de la Planta 3 a Morelia

La tarea consiste en plantear el problema de programación lineal que permita satisfacer las necesidades de todas las ciudades al tiempo que minimice los costos asociados a la distribución y resolverlo con `linprog`.

In [35]:
import numpy as np
import scipy.optimize as opt

In [36]:
c= np.array ([5,
             2,
             7,
             3,
             6,
             6,
             6,
             1,
             2])

A= np.array([[ 1,  1,  1,  0,  0,  0, 0, 0, 0], 
              [ 0,  0,  0,  1,  1,  1, 0, 0, 0], 
              [ 0,  0,  0,  0,  0,  0, 1, 1, 1],  
              [ -1,  0,  0,  -1,  0,  0, -1, 0, 0], 
              [ 0,  -1,  0,  0,  -1,  0, 0, -1, 0], 
              [ 0,  0,  -1,  0,  0,  -1, 0, 0, -1], ])

b = np.array ([80,
              40,
              60,
              -70,
              -40,
              -70])
respuesta = opt.linprog(c, A, b,  method="simplex")

In [37]:
respuesta.x

array([30., 40., 10., 40.,  0.,  0.,  0.,  0., 60.])

## 5. Optimización de inversión en bonos

**Referencia:**

El objetivo de este problema es determinar la mejor estrategia de inversión, dados diferentes tipos de bono, la máxima cantidad que puede ser invertida en cada bono, el porcentaje de retorno y los años de madurez. También hay una cantidad fija de dinero disponible ($\$750,000$). Por lo menos la mitad de este dinero debe ser invertido en bonos con 10 años o más para la madurez. Se puede invertir un máximo del $25\%$ de esta cantidad en cada bono. Finalmente, hay otra restricción que no permite usar más de $35\%$ en bonos de alto riesgo.

Existen seis (6) opciones de inversión con las letras correspondientes $A_i$

1. $A_1$:(Tasa de retorno=$8.65\%$; Años para la madurez=11, Riesgo=Bajo)
1. $A_2$:(Tasa de retorno=$9.50\%$; Años para la madurez=10, Riesgo=Alto)
1. $A_3$:(Tasa de retorno=$10.00\%$; Años para la madurez=6, Riesgo=Alto)
1. $A_4$:(Tasa de retorno=$8.75\%$; Años para la madurez=10, Riesgo=Bajo)
1. $A_5$:(Tasa de retorno=$9.25\%$; Años para la madurez=7, Riesgo=Alto)
1. $A_6$:(Tasa de retorno=$9.00\%$; Años para la madurez=13, Riesgo=Bajo)

Lo que se quiere entonces es maximizar el retorno que deja la inversión.

Este problema puede ser resuelto con programación lineal. Formalmente, puede ser descrito como:

$$\max_{A_1,A_2,...,A_6}\sum^{6}_{i=1} A_iR_i,$$

donde $A_i$ representa la cantidad invertida en la opción, y $R_i$ representa la tasa de retorno respectiva.

In [38]:
import numpy as np
import scipy.optimize as opt

In [39]:
c= np.array([-8.65,
            -9.50,
            -10,
            -8.75,
            -9.25,
            -9])
A = np.array([[ 0,  1,  1,  0,  1,  0], 
              [-1, -1,  0, -1,  0, -1], 
              [ 1,  0,  0,  0,  0,  0], 
              [ 0,  1,  0,  0,  0,  0], 
              [ 0,  0,  1,  0,  0,  0],
              [ 0,  0,  0,  1,  0,  0],
              [ 0,  0,  0,  0,  1,  0],
              [ 0,  0,  0,  0,  0,  1],
              [ 1,  1,  1,  1,  1,  1]])
b= np.array([262500,
            -375000,
            187500,
            187500,
            187500,
            187500,
            187500,
            187500,
            750000])
respuesta = opt.linprog(c, A, b, method="simplex")


In [40]:
respuesta.x

array([112500.,  75000., 187500., 187500.,      0., 187500.])